class ShampooRunner
{
public static void main(String[] shampoo)
{
  Shampoo ref = new Shampoo();
  ref.washCars();
  ref.brandName = "clinicplus";
  ref.id = 1;
  ref.color = "white";
  ref.quantity = 100;
  ref.price = 10.00;
  ref.mgfDate = "17/07/24";
  ref.expDate = "17/05/25";
   System.out.println("----------------------------------------------------------------");
  System.out.println("The Brand name is "+ ref.brandName);
  System.out.println("The color is "+ ref.color);
  System.out.println("The id is "+ ref.id);
  System.out.println("The quantity is "+ ref.quantity);
  System.out.println("The price is "+ ref.price);
  System.out.println("The mgfDate is "+ ref.mgfDate);
  System.out.println("The expDate is "+  ref.expDate);
  System.out.println("----------------------------------------------------------------");
   Shampoo ref1 = new Shampoo();
   ref1.washCars();
   ref1.brandName = "sunsilk";
   ref1.id = 2;
   ref1.color = "black";
    ref1.quantity = 10;
   ref1.price = 10;
    ref1.mgfDate = "14/07/24";
  ref1.expDate = "02/05/25";
  System.out.println("----------------------------------------------------------------");
   System.out.println("The Brand name is "+ ref1.brandName);
  System.out.println("The color is "+ ref1.color);
  System.out.println("The id is "+ ref1.id);
  System.out.println("The quantity is "+ ref1.quantity);
  System.out.println("The price is "+ ref1.price);
  System.out.println("The mgfDate is "+ ref1.mgfDate);
  System.out.println("The expDate is "+  ref1.expDate);
  System.out.println("----------------------------------------------------------------");
  Shampoo ref2 = new Shampoo();
  ref2.washCars();
   ref2.brandName = "dove";
   ref2.id = 2;
   ref2.color = "white";
    ref2.quantity = 20;
   ref2.price = 20;
    ref2.mgfDate = "19/07/24";
  ref2.expDate = "17/06/25";
  System.out.println("----------------------------------------------------------------");
    System.out.println("The Brand name is "+ ref2.brandName);
  System.out.println("The color is "+ ref2.color);
  System.out.println("The id is "+ ref2.id);
  System.out.println("The quantity is "+ ref.quantity);
  System.out.println("The price is "+ ref2.price);
  System.out.println("The mgfDate is "+ ref2.mgfDate);
  System.out.println("The expDate is "+  ref2.expDate);
  System.out.println("----------------------------------------------------------------");
   Shampoo ref3 = new Shampoo();
   ref3.washCars();
   ref3.brandName = "Pantene";
   ref3.id = 2;
   ref3.color = "black";
    ref3.quantity = 30;
   ref3.price = 10;
    ref3.mgfDate = "17/09/24";
  ref3.expDate = "17/08/25";
  System.out.println("----------------------------------------------------------------");
  System.out.println("The Brand name is "+ ref3.brandName);
  System.out.println("The color is "+ ref3.color);
  System.out.println("The id is "+ ref3.id);
  System.out.println("The quantity is "+ ref3.quantity);
  System.out.println("The price is "+ ref3.price);
  System.out.println("The mgfDate is "+ ref3.mgfDate);
  System.out.println("The expDate is "+  ref3.expDate);
  System.out.println("----------------------------------------------------------------");
  Shampoo ref4 = new Shampoo();
   ref4.washCars();
   ref4.brandName = "Loreal";
   ref4.id = 2;
   ref4.color = "white";
    ref4.quantity = 500;
   ref4.price = 50;
    ref4.mgfDate = "16/09/24";
  ref4.expDate = "07/08/25";
  System.out.println("----------------------------------------------------------------");
  System.out.println("The Brand name is "+ ref4.brandName);
  System.out.println("The color is "+ ref4.color);
  System.out.println("The id is "+ ref4.id);
  System.out.println("The quantity is "+ ref4.quantity);
  System.out.println("The price is "+ ref4.price);
  System.out.println("The mgfDate is "+ ref4.mgfDate);
  System.out.println("The expDate is "+  ref4.expDate);
  System.out.println("----------------------------------------------------------------");
   Shampoo ref5 = new Shampoo();
   ref5.washCars();
   ref5.brandName = "Head and shoulders";
   ref5.id = 2;
   ref5.color = "white";
    ref5.quantity = 50;
   ref5.price = 40;
    ref5.mgfDate = "09/08/24";
  ref5.expDate = "07/09/25";
  System.out.println("----------------------------------------------------------------");
  System.out.println("The Brand name is "+ ref5.brandName);
  System.out.println("The color is "+ ref5.color);
  System.out.println("The id is "+ ref5.id);
  System.out.println("The quantity is "+ ref5.quantity);
  System.out.println("The price is "+ ref5.price);
  System.out.println("The mgfDate is "+ ref5.mgfDate);
  System.out.println("The expDate is "+  ref5.expDate);
  System.out.println("------------------------------------------------------------------");
  Shampoo ref6 = new Shampoo();
   ref6.washCars();
   ref6.brandName = "Biolage";
   ref6.id = 2;
   ref6.color = "white";
    ref6.quantity = 50;
   ref6.price = 40;
    ref6.mgfDate = "09/08/24";
  ref6.expDate = "07/09/25";
  System.out.println("----------------------------------------------------------------");
  System.out.println("The Brand name is "+ ref6.brandName);
  System.out.println("The color is "+ ref6.color);
  System.out.println("The id is "+ ref6.id);
  System.out.println("The quantity is "+ ref6.quantity);
  System.out.println("The price is "+ ref6.price);
  System.out.println("The mgfDate is "+ ref6.mgfDate);
  System.out.println("The expDate is "+  ref6.expDate);
  System.out.println("------------------------------------------------------------------");
  Shampoo ref7 = new Shampoo();
   ref7.washCars();
   ref7.brandName = "Herbal Essences";
   ref7.id = 2;
   ref7.color = "white";
    ref7.quantity = 50;
   ref7.price = 40;
    ref7.mgfDate = "05/09/24";
  ref.expDate = "07/08/25";
  System.out.println("----------------------------------------------------------------");
  System.out.println("The Brand name is "+ ref7.brandName);
  System.out.println("The color is "+ ref7.color);
  System.out.println("The id is "+ ref7.id);
  System.out.println("The quantity is "+ ref7.quantity);
  System.out.println("The price is "+ ref7.price);
  System.out.println("The mgfDate is "+ ref7.mgfDate);
  System.out.println("The expDate is "+  ref7.expDate);
  System.out.println("------------------------------------------------------------------");
  Shampoo ref8 = new Shampoo();
   ref8.washCars();
   ref8.brandName = "Redken";
   ref8.id = 2;
   ref8.color = "white";
    ref8.quantity = 80;
   ref8.price = 90;
    ref8.mgfDate = "02/09/24";
  ref.expDate = "12/08/25";
  System.out.println("----------------------------------------------------------------");
  System.out.println("The Brand name is "+ ref8.brandName);
  System.out.println("The color is "+ ref8.color);
  System.out.println("The id is "+ ref8.id);
  System.out.println("The quantity is "+ ref8.quantity);
  System.out.println("The price is "+ ref8.price);
  System.out.println("The mgfDate is "+ ref8.mgfDate);
  System.out.println("The expDate is "+  ref8.expDate);
  System.out.println("------------------------------------------------------------------");
  Shampoo ref9 = new Shampoo();
   ref9.washCars();
   ref9.brandName = "TREsemme";
   ref9.id = 2;
   ref9.color = "white";
    ref9.quantity = 80;
   ref9.price = 90;
    ref9.mgfDate = "02/09/24";
  ref9.expDate = "12/08/25";
  System.out.println("----------------------------------------------------------------");
  System.out.println("The Brand name is "+ ref9.brandName);
  System.out.println("The color is "+ ref9.color);
  System.out.println("The id is "+ ref9.id);
  System.out.println("The quantity is "+ ref9.quantity);
  System.out.println("The price is "+ ref9.price);
  System.out.println("The mgfDate is "+ ref9.mgfDate);
  System.out.println("The expDate is "+  ref9.expDate);
  System.out.println("------------------------------------------------------------------");
  Shampoo ref10 = new Shampoo();
   ref10.washCars();
   ref10.brandName = "Garnier";
   ref10.id = 2;
   ref10.color = "white";
    ref10.quantity = 80;
   ref10.price = 90;
    ref10.mgfDate = "02/09/24";
  ref10.expDate = "12/08/25";
  System.out.println("----------------------------------------------------------------");
  System.out.println("The Brand name is "+ ref10.brandName);
  System.out.println("The color is "+ ref10.color);
  System.out.println("The id is "+ ref10.id);
  System.out.println("The quantity is "+ ref10.quantity);
  System.out.println("The price is "+ ref10.price);
  System.out.println("The mgfDate is "+ ref10.mgfDate);
  System.out.println("The expDate is "+  ref10.expDate);
  System.out.println("------------------------------------------------------------------");
  Shampoo ref11 = new Shampoo();
   ref11.washCars();
   ref11.brandName = "Garnier";
   ref11.id = 7;
   ref11.color = "white";
    ref11.quantity = 90;
   ref11.price = 70;
    ref11.mgfDate = "01/10/24";
  ref11.expDate = "12/11/25";
  System.out.println("----------------------------------------------------------------");
  System.out.println("The Brand name is "+ ref11.brandName);
  System.out.println("The color is "+ ref11.color);
  System.out.println("The id is "+ ref11.id);
  System.out.println("The quantity is "+ ref11.quantity);
  System.out.println("The price is "+ ref11.price);
  System.out.println("The mgfDate is "+ ref11.mgfDate);
  System.out.println("The expDate is "+  ref11.expDate);
  System.out.println("------------------------------------------------------------------");
   Shampoo ref12 = new Shampoo();
   ref12.washCars();
   ref12.brandName = "Organix";
   ref12.id = 7;
   ref12.color = "white";
    ref12.quantity = 90;
   ref12.price = 70;
    ref12.mgfDate = "07/10/24";
  ref12.expDate = "12/11/25";
  System.out.println("----------------------------------------------------------------");
  System.out.println("The Brand name is "+ ref12.brandName);
  System.out.println("The color is "+ ref12.color);
  System.out.println("The id is "+ ref12.id);
  System.out.println("The quantity is "+ ref12.quantity);
  System.out.println("The price is "+ ref12.price);
  System.out.println("The mgfDate is "+ ref12.mgfDate);
  System.out.println("The expDate is "+  ref12.expDate);
  System.out.println("------------------------------------------------------------------");
  Shampoo ref13 = new Shampoo();
   ref13.washCars();
   ref13.brandName = "Schwarzkopf";
   ref13.id = 7;
   ref13.color = "white";
    ref13.quantity = 90;
   ref13.price = 70;
    ref13.mgfDate = "09/11/24";
  ref13.expDate = "12/12/25";
  System.out.println("----------------------------------------------------------------");
  System.out.println("The Brand name is "+ ref13.brandName);
  System.out.println("The color is "+ ref13.color);
  System.out.println("The id is "+ ref13.id);
  System.out.println("The quantity is "+ ref13.quantity);
  System.out.println("The price is "+ ref13.price);
  System.out.println("The mgfDate is "+ ref13.mgfDate);
  System.out.println("The expDate is "+  ref13.expDate);
  System.out.println("------------------------------------------------------------------");
  Shampoo ref14 = new Shampoo();
   ref14.washCars();
   ref14.brandName = "Aveda";
   ref14.id = 7;
   ref14.color = "white";
    ref14.quantity = 90;
   ref14.price = 400;
    ref14.mgfDate = "09/11/24";
  ref13.expDate = "12/12/25";
  System.out.println("----------------------------------------------------------------");
  System.out.println("The Brand name is "+ ref14.brandName);
  System.out.println("The color is "+ ref14.color);
  System.out.println("The id is "+ ref14.id);
  System.out.println("The quantity is "+ ref14.quantity);
  System.out.println("The price is "+ ref14.price);
  System.out.println("The mgfDate is "+ ref14.mgfDate);
  System.out.println("The expDate is "+  ref14.expDate);
  System.out.println("------------------------------------------------------------------");
  }
  }