class SimCardRunner
{
 public static void main(String[] simcard)
  {
      SimCard ref = new SimCard();
	 ref.communication();
	 ref.name = "airtel";
  ref.id = 1;
  ref.plan = "250";
  ref.price = 100;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref.name);
  System.out.println("The id is "+ ref.id);
  System.out.println("The plan is "+ ref.plan);
  System.out.println("The price is "+ ref.price);
  System.out.println("--------------------------------------------------");
  SimCard ref1 = new SimCard();
	 ref1.communication();
	 ref1.name = "VI";
  ref1.id = 2;
  ref1.plan = "350";
  ref1.price = 200;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref1.name);
  System.out.println("The id is "+ ref1.id);
  System.out.println("The plan is "+ ref1.plan);
  System.out.println("The price is "+ ref1.price);
  System.out.println("--------------------------------------------------");
  SimCard ref2 = new SimCard();
	 ref2.communication();
	 ref2.name = "idea";
  ref2.id = 3;
  ref2.plan = "150";
  ref2.price = 300;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref2.name);
  System.out.println("The id is "+ ref2.id);
  System.out.println("The plan is "+ ref2.plan);
  System.out.println("The price is "+ ref2.price);
  System.out.println("--------------------------------------------------");
  SimCard ref3 = new SimCard();
	 ref3.communication();
	 ref3.name = "Nokia";
  ref3.id = 4;
  ref3.plan = "250";
  ref3.price = 300;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref3.name);
  System.out.println("The id is "+ ref3.id);
  System.out.println("The plan is "+ ref3.plan);
  System.out.println("The price is "+ ref3.price);
  System.out.println("--------------------------------------------------");
  SimCard ref4 = new SimCard();
	 ref4.communication();
	 ref4.name = "Jio";
  ref4.id = 4;
  ref4.plan = "210";
  ref4.price = 200;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref4.name);
  System.out.println("The id is "+ ref4.id);
  System.out.println("The plan is "+ ref4.plan);
  System.out.println("The price is "+ ref4.price);
  System.out.println("--------------------------------------------------");
  SimCard ref5 = new SimCard();
	 ref5.communication();
	 ref5.name = "BSNL";
  ref5.id = 5;
  ref5.plan = "280";
  ref5.price = 300;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref5.name);
  System.out.println("The id is "+ ref5.id);
  System.out.println("The plan is "+ ref5.plan);
  System.out.println("The price is "+ ref5.price);
  System.out.println("--------------------------------------------------");
  SimCard ref6 = new SimCard();
	 ref6.communication();
	 ref6.name = "(TTBS)";
  ref6.id = 5;
  ref6.plan = "280";
  ref6.price = 300;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref6.name);
  System.out.println("The id is "+ ref6.id);
  System.out.println("The plan is "+ ref6.plan);
  System.out.println("The price is "+ ref6.price);
  System.out.println("-------------------------------------------------");
  SimCard ref7 = new SimCard();
	 ref7.communication();
	 ref7.name = "MTNL";
  ref7.id = 7;
  ref7.plan = "380";
  ref7.price = 200;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref7.name);
  System.out.println("The id is "+ ref7.id);
  System.out.println("The plan is "+ ref7.plan);
  System.out.println("The price is "+ ref7.price);
  System.out.println("--------------------------------------------------");
  SimCard ref8 = new SimCard();
	 ref8.communication();
	 ref8.name = "Aircel";
  ref8.id = 8;
  ref8.plan = "480";
  ref8.price = 250;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref8.name);
  System.out.println("The id is "+ ref8.id);
  System.out.println("The plan is "+ ref8.plan);
  System.out.println("The price is "+ ref8.price);
  System.out.println("--------------------------------------------------");
  SimCard ref9 = new SimCard();
	 ref9.communication();
	 ref9.name = "MTNL";
  ref9.id = 7;
  ref9.plan = "380";
  ref9.price = 200;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref9.name);
  System.out.println("The id is "+ ref9.id);
  System.out.println("The plan is "+ ref9.plan);
  System.out.println("The price is "+ ref9.price);
  System.out.println("--------------------------------------------------");
  SimCard ref10 = new SimCard();
	 ref10.communication();
	 ref10.name = "Tray";
  ref10.id = 8;
  ref10.plan = "500";
  ref10.price = 700;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref10.name);
  System.out.println("The id is "+ ref10.id);
  System.out.println("The plan is "+ ref10.plan);
  System.out.println("The price is "+ ref10.price);
  System.out.println("--------------------------------------------------");
  SimCard ref11 = new SimCard();
	 ref11.communication();
	 ref11.name = "4G LTE";
  ref11.id = 7;
  ref11.plan = "600";
  ref11.price = 300;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref11.name);
  System.out.println("The id is "+ ref11.id);
  System.out.println("The plan is "+ ref11.plan);
  System.out.println("The price is "+ ref11.price);
  System.out.println("--------------------------------------------------");
  SimCard ref12 = new SimCard();
	 ref12.communication();
	 ref12.name = "iphone5";
  ref12.id = 9;
  ref12.plan = "680";
  ref12.price = 500;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref12.name);
  System.out.println("The id is "+ ref12.id);
  System.out.println("The plan is "+ ref12.plan);
  System.out.println("The price is "+ ref12.price);
  System.out.println("--------------------------------------------------");
  SimCard ref13 = new SimCard();
	 ref13.communication();
	 ref13.name = "Samsung";
  ref13.id = 7;
  ref13.plan = "580";
  ref13.price = 500;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref13.name);
  System.out.println("The id is "+ ref13.id);
  System.out.println("The plan is "+ ref13.plan);
  System.out.println("The price is "+ ref13.price);
  System.out.println("--------------------------------------------------");
  SimCard ref14 = new SimCard();
	 ref14.communication();
	 ref14.name = "Videocon";
  ref14.id = 14;
  ref14.plan = "480";
  ref14.price = 300;
  System.out.println("-------------------------------------------------");
  System.out.println("The Brand name is "+ ref14.name);
  System.out.println("The id is "+ ref14.id);
  System.out.println("The plan is "+ ref14.plan);
  System.out.println("The price is "+ ref14.price);
  System.out.println("--------------------------------------------------");
  }
  }
  
  
  
  
  
  
  
  
  
  